package pit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import javax.jms.*;
import javax.naming.*;

/*
 * This is the ONLY file that you are to edit.  It is the model of play for
 * every PITplayer.  Each PITplayer instantiates this model and uses it to
 * process the messages it receives.
 */
public class PITPlayerModel {

    // Each PITplayer has a unique myPlayerNumber.  It is set in the PITPlayer constructor.
    private int myPlayerNumber;
    // Cards is this player's set of cards.  
    private final ArrayList cards = new ArrayList();
    // numTrades counts trades.
    private int numTrades = 0;
    // maxTrades is the maximum number of trades, after which trading is stopped.
    private final int maxTrades = 20000;
    // numPlayers are the number of Players trading.  This comes with a NewHand from the PITsnapshot servlet
    private int numPlayers = 0;
    // halting indicates that the system is being reset, so ignore trades unti a new had received.
    private boolean halting = false;
    // initiating an ArrayList to store the incoming markers for the player
    private final ArrayList<Integer> markers = new ArrayList<Integer>();

    /* The snapshot servlet (PITsnapshot) is expecting to be passed an ObjectMessage
     * where the object is a HashMap. Therefore this definition of that HashMap is 
     * provided although it is not currently used (it is for you to use).
     * PITsnapshot is expecting a set of attibute/value pairs.  These include the player
     * number, as in state.put("Player", myPlayerNumber), and each commodity string
     * and the number of that commodity in the snapshot.
     * Also included below is a utility method that will turn a HashMap into a string
     * which is useful for printing diagnostic messages to the console.
     */
    private HashMap<String, Integer> state = new HashMap();

    // PITPlayerModel constructor saves what number player this object represents.
    PITPlayerModel(int myNumber) {
        myPlayerNumber = myNumber;
    }

    /**
     * onMessage public method to deal with the incoming message
     * @param message the message received by the player
     */
    public void onMessage(Message message) {
        try {
            if (message instanceof ObjectMessage) {
                Object o = ((ObjectMessage) message).getObject();

                // There are 4 types of messages:  Reset, NewHand, Trade, and Marker
                // Reset the Player.  The Reset message is generated by the PITsnapshot servlet
                if (o instanceof Reset) {
                    doReset((Reset) o);

                    // NewHand received from PITsnapshot
                } else if (o instanceof NewHand) {
                    // Add the new hand into cards
                    doNewHand((NewHand) o);

                    // Receive a Trade from another Player
                } else if (o instanceof Trade) {
                    // Add the trade into cards
                    doReceiveTrade((Trade) o);
                }else{
                    // Add Markers to the outgoing channel if it is the first marker the player received
                    // Then close recording this channel's records.
                    doMarker((Marker) o);
                }
            }
        } catch (Exception e) {
            System.out.println("Exception thrown in PITplayer" + myPlayerNumber + ": " + e);
        }
    }

    /**
     * doMarker private method deals with the message whose type is Marker, does the operations the player needs when receive markers
     * @param marker the marker message received by the player
     */
    private void doMarker(Marker marker) throws Exception{
        // check, if the marker is from the monitor with the value -1 or the ArrayList doesn't
        //have it yet, add it into the ArrayList; else, do not add the marker
        if (marker.source!=-1 && !markers.contains(marker.source)){
            markers.add(marker.source);
        }
 
        // check if the state is empty means that this marker is the first marker received by the player
        // if it is the first marker, the player stores all the items in the cards (its current state) into state
        // and send markers to all the other players
        if (state.isEmpty()){
            state.put("Player", myPlayerNumber);

            // calculate key-value pair in state and put records of each item into state
            for(int i=0;i<cards.size();i++){
                if(state.containsKey((String)cards.get(i))){
                    state.put((String)cards.get(i),state.get((String)cards.get(i))+1);
                }else{
                    state.put((String)cards.get(i),1);
                }
            }

            // send markers to all other 4 players (except this player itself)
            for(int i=0;i<5;i++){
               if(i!=myPlayerNumber){  
                    Marker m = new Marker(myPlayerNumber);
                    sendToQueue("jms/PITplayer"+i, m);
                }
            }
        }
        
        // send the player's state to the snapshot queue when the player has received markers from all the incoming channel
        // (which represents by the size of the marker ArrayList is equal to 4)
        if(markers.size()==4){
            sendToQueue("jms/PITsnapshot", state);
            // clear the current state and markers
            state.clear();
            markers.clear();
        }
    }
    
    /**
     * doReset private method deals with the message whose type is Reset, resets all the things for the player (e.g. clear the cards)
     * @param reset the reset message received by the player
     */
    private void doReset(Reset reset) throws Exception {
        if (reset.action == Reset.HALT) {
            System.out.println("PITplayer" + myPlayerNumber + " received Reset HALT");
            halting = true;
            // Reply to the PITsnapshot servlet acknowledging the Reset HALT
            sendToQueue("jms/PITmonitor", reset);
        } else { // action == Reset.CLEAR
            System.out.println("PITplayer" + myPlayerNumber + " received Reset RESET");
            // Drop all cards in hand
            cards.clear();
            numTrades = 0;
            numPlayers = 0;
            halting = false;
            // Reply to the PITsnapshot servlet acknowledging the Reset
            sendToQueue("jms/PITmonitor", reset);
        }
    }

    /**
     * doNewhand private method deals with the message whose type is NewHand, gives the player the initial items
     * @param hand the NewHand message received by the player
     */
    private void doNewHand(NewHand hand) throws Exception {
        // Add new hand cards.  
        // It is actually possible that a trade had added a card already.
        cards.addAll((hand).newHand);
        numPlayers = (hand).numPlayers;
        System.out.println("PITplayer" + myPlayerNumber + " new hand: " + toString(cards));
        // Trade away a card
        doMakeTrade();
    }

    /**
     * doReceiveTrade private method deals with the message whose type is Trade, adds trade to cards and check if the trade should be put into state
     * @param trade the Trade message received by the player
     */
    private void doReceiveTrade(Trade trade) throws Exception {
        if (halting) return; // if halting, discard trade

        // Having received a Trade card from another Player, add it to my hand of cards
        cards.add(trade.tradeCard);

        System.out.println("PITplayer" + myPlayerNumber + " received: " + trade.tradeCard + " from player: " + trade.sourcePlayer);
        System.out.println("PITplayer" + myPlayerNumber + " hand: " + toString(cards));
        
        if(!state.isEmpty() && !markers.contains(trade.sourcePlayer) && markers.size()!=4){
            if(state.containsKey(trade.tradeCard)){
                    state.replace(trade.tradeCard,state.get(trade.tradeCard)+1);
                }else{
                    state.put(trade.tradeCard,1);
                }
        }
        // Trade away a card
        doMakeTrade();
    }

    /**
     * doMakeTrade private method makes a trade to the other players
     */
    private void doMakeTrade() throws Exception {

        // if hit maxTrades limit, then stop sending trades
        if (maxTrades(maxTrades)) {
            return;
        }

        /*
         * If numPlayers == 0, while we have received a Trade, we have not 
         * received our NewHand yet, so we don't know how many players there 
         * are.  Therefore, don't send out a Trade at this time.
         * 
         */
        if (numPlayers == 0) {
            return;
        }

        // Create a new Trade from my set of cards, and send to another player
        Trade newTrade = new Trade();
        newTrade.tradeCard = (String) cards.remove(0);
        newTrade.sourcePlayer = myPlayerNumber;

        // Find a random player to trade to (not including myself)
        int sendTo = myPlayerNumber;
        while (sendTo == myPlayerNumber) {
            sendTo = Math.round((float) Math.random() * (numPlayers - 1));
        }

        //Send the card to the other player
        System.out.println("PITplayer" + myPlayerNumber + " sending: " + newTrade.tradeCard + " to player: " + sendTo);
        String sendToJNDI = "jms/PITplayer" + sendTo;
        sendToQueue(sendToJNDI, newTrade);

    }

    // Create a string of hand size and all cards to use in printing
    private String toString(ArrayList hand) {

        String cardsString = "size: " + hand.size() + " ";
        for (int i = 0; i < hand.size(); i++) {
            cardsString += hand.get(i) + " ";
        }
        return cardsString;
    }

    // Create a printable version of the "state".
    private String toString(HashMap<String, Integer> state) {
        String stateString = "";
        for (Iterator it = state.entrySet().iterator(); it.hasNext();) {
            Map.Entry entry = (Map.Entry) it.next();
            String commodity = (String) entry.getKey();
            int number = ((Integer) entry.getValue()).intValue();
            stateString += "{" + commodity + ":" + number + "} ";
        }
        return stateString;
    }

    // Send an object to a Queue, given its JNDI name
    private void sendToQueue(String queueJNDI, Serializable message) throws Exception {
        // Gather necessary JMS resources
        Context ctxt = new InitialContext();
        Connection con = ((ConnectionFactory) ctxt.lookup("jms/myConnectionFactory")).createConnection();
        Session session = con.createSession(false, Session.AUTO_ACKNOWLEDGE);
        Queue q = (Queue) ctxt.lookup(queueJNDI);
        MessageProducer writer = session.createProducer(q);
        ObjectMessage msg = session.createObjectMessage(message);
        // Send the object to the Queue
        writer.send(msg);
        session.close();
        con.close();
        ctxt.close();
    }

    // Stop trading when the max number of Trades is reached
    private boolean maxTrades(int max) {
        if ((numTrades % 100) == 0) {
            System.out.println("PITplayer" + myPlayerNumber + " tradeCount: " + numTrades);
        }
        return (numTrades++ < max) ? false : true;
    }
}
